INSERT INTO `colors`(`id`, `created_at`, `updated_at`, `name`, `color_code`) VALUES
                                                                                 (1, NOW(), NOW(), 'Red', '#FF0000'),
                                                                                 (2, NOW(), NOW(), 'Blue', '#0000FF'),
                                                                                 (3, NOW(), NOW(), 'Green', '#008000'),
                                                                                 (4, NOW(), NOW(), 'Black', '#000000'),
                                                                                 (5, NOW(), NOW(), 'White', '#FFFFFF'),
                                                                                 (6, NOW(), NOW(), 'Yellow', '#FFFF00'),
                                                                                 (7, NOW(), NOW(), 'Purple', '#800080'),
                                                                                 (8, NOW(), NOW(), 'Orange', '#FFA500'),
                                                                                 (9, NOW(), NOW(), 'Pink', '#FFC0CB'),
                                                                                 (10, NOW(), NOW(), 'Brown', '#A52A2A'),
                                                                                 (11, NOW(), NOW(), 'Cyan', '#00FFFF'),
                                                                                 (12, NOW(), NOW(), 'Magenta', '#FF00FF'),
                                                                                 (13, NOW(), NOW(), 'Silver', '#C0C0C0'),
                                                                                 (14, NOW(), NOW(), 'Gold', '#FFD700'),
                                                                                 (15, NOW(), NOW(), 'Beige', '#F5F5DC'),
                                                                                 (16, NOW(), NOW(), 'Gray', '#808080'),
                                                                                 (17, NOW(), NOW(), 'Lavender', '#E6E6FA'),
                                                                                 (18, NOW(), NOW(), 'Olive', '#808000'),
                                                                                 (19, NOW(), NOW(), 'Teal', '#008080'),
                                                                                 (20, NOW(), NOW(), 'Navy', '#000080');
INSERT INTO `sizes`(`id`, `created_at`, `updated_at`, `name`) VALUES
                                                                  (1, NOW(), NOW(), 'XS'),
                                                                  (2, NOW(), NOW(), 'S'),
                                                                  (3, NOW(), NOW(), 'M'),
                                                                  (4, NOW(), NOW(), 'L'),
                                                                  (5, NOW(), NOW(), 'XL'),
                                                                  (6, NOW(), NOW(), 'XXL'),
                                                                  (7, NOW(), NOW(), 'XXXL'),
                                                                  (8, NOW(), NOW(), '4XL'),
                                                                  (9, NOW(), NOW(), '5XL'),
                                                                  (10, NOW(), NOW(), '6XL'),
                                                                  (11, NOW(), NOW(), '28'),
                                                                  (12, NOW(), NOW(), '30'),
                                                                  (13, NOW(), NOW(), '32'),
                                                                  (14, NOW(), NOW(), '34'),
                                                                  (15, NOW(), NOW(), '36'),
                                                                  (16, NOW(), NOW(), '38'),
                                                                  (17, NOW(), NOW(), '40'),
                                                                  (18, NOW(), NOW(), '42'),
                                                                  (19, NOW(), NOW(), '44'),
                                                                  (20, NOW(), NOW(), '46');
INSERT INTO categories (id, name, description) VALUES
                                                   (1, 'Books', 'Various genres of books including fiction, non-fiction, and academic.'),
                                                   (2, 'Clothes', 'Men, women, and children clothing of all styles.'),
                                                   (3, 'Electronics', 'Gadgets, mobile phones, laptops, and more.'),
                                                   (4, 'Home Appliances', 'Essential appliances for home use.'),
                                                   (5, 'Furniture', 'Chairs, tables, sofas, and other furniture.'),
                                                   (6, 'Toys', 'Kids’ toys, puzzles, and board games.'),
                                                   (7, 'Sports Equipment', 'Items for fitness, outdoor, and indoor sports.'),
                                                   (8, 'Beauty & Personal Care', 'Skincare, makeup, and personal care products.'),
                                                   (9, 'Health & Wellness', 'Supplements, fitness gear, and medical supplies.'),
                                                   (10, 'Automotive', 'Car accessories, tools, and spare parts.'),
                                                   (11, 'Music & Instruments', 'Musical instruments and accessories.'),
                                                   (12, 'Movies & Entertainment', 'DVDs, Blu-ray, and streaming accessories.'),
                                                   (13, 'Gaming', 'Consoles, accessories, and gaming-related items.'),
                                                   (14, 'Pet Supplies', 'Food, toys, and accessories for pets.'),
                                                   (15, 'Groceries', 'Daily essentials, food, and beverages.'),
                                                   (16, 'Office Supplies', 'Stationery, printers, and office accessories.'),
                                                   (17, 'Garden & Outdoor', 'Plants, tools, and outdoor furniture.'),
                                                   (18, 'Jewelry & Watches', 'Luxury and fashion jewelry, wristwatches.'),
                                                   (19, 'Handmade & Crafts', 'DIY craft supplies and handmade items.'),
                                                   (20, 'Baby Products', 'Clothing, toys, and essentials for babies.');
